"""empty message

Revision ID: b33d9b716926
Revises: c3249564192c
Create Date: 2023-09-20 03:44:23.678984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33d9b716926'
down_revision = 'c3249564192c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('class_name', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_student_id'), ['student_id'], unique=True)
        batch_op.drop_column('gpa')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_teacher_teacher_id'), ['teacher_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_id'))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_student_student_id'))
        batch_op.drop_column('class_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('school')
    # ### end Alembic commands ###
