"""empty message

Revision ID: f728adf5a5ff
Revises: 04130dce5db6
Create Date: 2023-09-22 17:05:35.708827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f728adf5a5ff'
down_revision = '04130dce5db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_fk', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('school_fk', 'school', ['school_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('school_fk', 'school', ['school_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint('unique_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint('school_fk', type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('school_fk', type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint('user_fk', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
